// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLgh05Dp6vxXwG07FB2V0US6bxUEjtgcI',
    appId: '1:383937941740:web:e7fda2c2629dfa0f9315c9',
    messagingSenderId: '383937941740',
    projectId: 'chatfonsti',
    authDomain: 'chatfonsti.firebaseapp.com',
    storageBucket: 'chatfonsti.appspot.com',
    measurementId: 'G-KT48HZYJS4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0xDoMQmGzX0sioxfCY_vZiLqoo8eMjXI',
    appId: '1:383937941740:android:378b235f65c397969315c9',
    messagingSenderId: '383937941740',
    projectId: 'chatfonsti',
    storageBucket: 'chatfonsti.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBR3-C1Mijpj3HWRjWIlBVvZpUSylFX3BE',
    appId: '1:383937941740:ios:69ec15df778215d09315c9',
    messagingSenderId: '383937941740',
    projectId: 'chatfonsti',
    storageBucket: 'chatfonsti.appspot.com',
    iosBundleId: 'com.example.documentSharing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBR3-C1Mijpj3HWRjWIlBVvZpUSylFX3BE',
    appId: '1:383937941740:ios:69ec15df778215d09315c9',
    messagingSenderId: '383937941740',
    projectId: 'chatfonsti',
    storageBucket: 'chatfonsti.appspot.com',
    iosBundleId: 'com.example.documentSharing',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLgh05Dp6vxXwG07FB2V0US6bxUEjtgcI',
    appId: '1:383937941740:web:d4a1477ff4fd25639315c9',
    messagingSenderId: '383937941740',
    projectId: 'chatfonsti',
    authDomain: 'chatfonsti.firebaseapp.com',
    storageBucket: 'chatfonsti.appspot.com',
    measurementId: 'G-8VDNGSBDCB',
  );
}
